### ISSUE TITLE
Are you missing a call to unregisterReceiver()

### ISSUE THREAD

**Issue by urbanMar** [keiferstone/nonet#3]
Hi,

i have error:
_" has leaked IntentReceiver com.keiferstone.nonet.Monitor that was originally registered here. Are you _missing a call to unregisterReceiver()?"__

I have implemented NoNet BaseActivity.

Do U have any idea?

**Comment by keiferstone** [comment]
Are you calling NoNet.stopMonitoring()?

**Comment by urbanMar** [comment]
stopMonitoring() is implemented in onStop so it should be stopped when I change activity.
Is there any method to check is monitor is working?  If not I will create a fork and add this functionality

**Comment by keiferstone** [comment]
You should see logs whenever there is a connectivity event while a monitor is running. If you show me your BaseActivity code I might be more help.

**Comment by urbanMar** [comment]
I think that add getter for monitor would help, base on this there will be possibility of check nullity of object

Base code:
`
public abstract class CommonActivity<VM extends CommonViewModel> extends AppCompatActivity {

    public VM viewModel;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        bindData();
    }


    @Override
    protected void onStart() {
        viewModel.onStart();
        try {
            NoNet.monitor(this)
                    .poll()
                    .snackbar(R.string.no_internet)
                    .start();
        } catch (Exception e){
            e.printStackTrace();
        }

        super.onStart();
    }

    protected abstract void bindData();

    @Override
    protected void onStop() {
        viewModel.onStop();
        try {
            NoNet.stopMonitoring();
        } catch (Exception e){
            e.printStackTrace();
        }

        super.onStop();
    }

    protected void setupToolbar(Toolbar toolbar, boolean showBackButton) {
        if (toolbar != null) {
            setSupportActionBar(toolbar);
            setBackArrow(showBackButton);
        }
    }

    protected void setBackArrow(boolean showBackButton) {
        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(showBackButton);
            getSupportActionBar().setDisplayShowHomeEnabled(showBackButton);
        }

    }

    protected void setupToolbar(Toolbar toolbar) {
        setupToolbar(toolbar, true);
    }

}
`

**Comment by keiferstone** [comment]
I don't see any problems at a glance. My initial guess would be that you're overriding onStop in a subclass without calling super.onStop(). You could try running the debugger with a breakpoint in Monitor.unregisterConnectivityReceiver() to see if it's getting called.

**Comment by keiferstone** [comment]
I think this is a problem with onStart in a new Activity being called before onStop of an old Activity. I added a call to stopMonitoring in NoNet.monitor() that should cleanup old monitors and prevent leaks. This will be available in 1.2.4 which should go live in the next couple of hours.

Alternatively, you could move NoNet.monitor() to onResume() and NoNet.stopMonitoring() to onPause().

Let me know if this fixes your issue.

**Comment by keiferstone** [comment]
@urbanMar I released v2.0.0, which pulls in monitor lifecycle management. You no longer need to handle starting/stopping monitors as this is now handled by NoNet. Monitors are created the same way as before, only now you should create them in onCreate() instead of onStart() or onResume().
